# file: C:\Users\rudra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\graphql\error\graphql_error.py
# hypothesis_version: 6.135.14

['GraphQLError', 'Node', 'Source', 'SourceLocation', 'extensions', 'locations', 'message', 'nodes', 'original_error', 'path', 'positions', 'source']